# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - myLayersApi

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
    VERSION_NUMBER: '1.0.7'
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1'
          include-prerelease: true
     
     
      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: 'Get Version'
        id: version
        uses: battila7/get-version-action@v2
      - name: Pack common.sismo
        run: dotnet pack common.sismo\common.sismo\common.sismo.csproj --include-symbols --configuration Release -p:PackageVersion=${{ env.VERSION_NUMBER  }} -o "./packages" 
      - name: Pack clientlib.mylayers
        run: dotnet pack clientlib.mylayers\clientlib.mylayers.csproj  --configuration Release -p:PackageVersion=${{ env.VERSION_NUMBER  }} -o "./packages" 
      - name: Pack client.mylayersapi
        run: dotnet pack client.mylayersapi\client.mylayersapi.csproj  --configuration Release -p:PackageVersion=${{ env.VERSION_NUMBER  }} -o "./packages" 
     
      - name: Push generated package to GitHub registry common.sismo
        run: dotnet nuget push D:\a\mylayerapi\mylayerapi\packages\common.sismo.${{ env.VERSION_NUMBER }}.nupkg  --api-key ${{ secrets.GITHUB_TOKEN  }} --source https://nuget.pkg.github.com/igormatos02/index.json 
      
      - name: Push generated package to GitHub registry clientlib.mylayers
        run: dotnet nuget push D:\a\mylayerapi\mylayerapi\packages\clientlib.mylayersapi.${{ env.VERSION_NUMBER }}.nupkg  --api-key ${{ secrets.GITHUB_TOKEN  }} --source https://nuget.pkg.github.com/igormatos02/index.json 
        
      - name: Push generated package to GitHub registry client.mylayersapi
        run: dotnet nuget push D:\a\mylayerapi\mylayerapi\packages\client.mylayersapi.${{ env.VERSION_NUMBER }}.nupkg  --api-key ${{ secrets.GITHUB_TOKEN  }} --source https://nuget.pkg.github.com/igormatos02/index.json 

        
      
    
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'myLayersApi'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_BF8657C887474DCF9BE73F195F13F35C }}
          package: .
